<?php

namespace Database\Seeders;

use App\Models\FileType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FileTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        FileType::insert([
            [
                'file_name'=>'HojaVidaFuncionPublica',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'DeclaracionJuramentadaLey4de1992',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'VerificacionInhabilidadDelitoSexual',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'AutorizacionNotificacionCorreoElec',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'CompromisoInstitucionalVinculacion',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'AutorizacionTratamientoDatPer',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'VisaExtranjeria',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'FotocopiaLibretaMilitar',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'TarjetaProfesional',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'MatriculaProfesional',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'AvalSST',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'CertificadoCursandoPosgrado',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'CertificadoSegundaLengua',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'ExperienciaLaboral',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'AntecedentesDisciplinariosProcuraduria',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'AntecedenteFiscalContraloria',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'AntecedenteJudicialPoliciaNal',
                'fk_folder_type'=>'1'
            ],
            [
                'file_name'=>'FormatoAfiliacionSeguridadSocial',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'FormularioAfiliacionEps',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'FormularioAfiliacionPension',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'CertificadoCuentaBancaria',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'CertificadoAfiliacionUltimaEPS',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'CertificadoAfiliacionFondoPensiones',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'CedulaCiudadania',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'DeclaPensionadoSolPensionenTramite',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'AsignaturasDiasHorarios',
                'fk_folder_type'=>'2'
            ],
            [
                'file_name'=>'ResolucionNombramiento',
                'fk_folder_type'=>'2'
            ]
        ]);
    }
}
